import type { Metadata } from "next";
import Image from 'next/image'
import { Poppins } from "next/font/google";
import "./globals.css";

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '500', '700', '800', '900'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const RootLayout = ({ children }: Readonly<{ children: React.ReactNode }>) => {
  return (
    <html lang="es">
      <body className={poppins.className}>
        <div className="relative">
          <div className="absolute inset-0 z-0 pointer-events-none">
            <Image src="/bg.svg" className="w-full h-full object-cover opacity-40" alt="background" width={'100'} height={'100'} />
          </div>
          <div className="relative z-10">{children}</div>
        </div>
      </body>
    </html>
  );
};

export default RootLayout;
